### ISSUE TITLE
Fix movement

### ISSUE THREAD

**Issue by tedigdobreva** [shrike/game-dev-pizza#3]
Keep track of the order in which movement direction keys were pressed, so that if you press multiple direction keys and then release some of them, the movement will continue in the last pressed direction.

**Comment by Anarcroth** [comment]
dae

**Comment by Anarcroth** [comment]
6stane

**Comment by plamenbotev** [comment]
nice

**Comment by Anarcroth** [comment]
tested locally on firefox for 5 minutes. No bugs found. Pushed to master.
> fixed
